spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-233-174-23.compute-1.amazonaws.com/d5rkqdrd5bs85p
  username: sucehigfwraort
  password: a605b1648ef0152067f5665aef500ee83493a1022a895915a8c5f7c93fbb1837
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fndlwl64.sns-community-2023.secret-key
  token.expired-time-ms: 2592000000 # 30 days
