spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: update
  properties.hibernate.format_sql: true
  show-sql: true

spring.datasource:
  hikari.maximum-pool-size: 4
  url: jdbc:postgresql://ec2-3-233-174-23.compute-1.amazonaws.com/d5rkqdrd5bs85p
  username: sucehigfwraort
  password: a605b1648ef0152067f5665aef500ee83493a1022a895915a8c5f7c93fbb1837
  platform: postgres
  driver-class-name: org.postgresql.Driver

jwt:
  secret-key: fndlwl64.sns-community-2023.secret-key
  token.expired-time-ms: 2592000000 # 30 days

spring.redis.url: redis://:p65eb9a1e5ea9aa81b9ce30ebec492ac27e63a94e6a0d7cdd445c52f812f2e5b9@ec2-44-193-33-108.compute-1.amazonaws.com:27489


spring:
  kafka:
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: SCRAM-SHA-256
      sasl.jaas.config: org.apache.kafka.common.security.scram.ScramLoginModule required username="zegfrtmz" password="ju5WzeQTTWc-_LfDMZVP4xESGcmj1SBA";
    consumer:
      properties.spring.json.trusted.packages: "*"
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      group-id: alarm
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    listener:
      ack-mode: MANUAL
    producer:
      bootstrap-servers: dory-01.srvs.cloudkafka.com:9094, dory-02.srvs.cloudkafka.com:9094, dory-03.srvs.cloudkafka.com:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties.enable.idempotence: false
    topic:
      alarm: zegfrtmz-alarm